[package]
name = "square_encoder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
contour_tracing = { version = "*", features = ["image"] }
crypto-hash = "0.3.4"
image = "0.24.7"
rand = "0.8.5"
